[package]
name = "prex-challenge"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.14.1"
chrono = "0.4.45"
rust_decimal = { version = "1.42.1", features = ["serde-with-arbitrary-precision"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "1.0.151", features = ["arbitrary_precision"] }
